language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.dev.txt
  - pip install coveralls

env:
  global:
  - TRAVIS="True"

script:
  - nosetests --with-coverage --cover-package=helium

after_success:
  coveralls

notifications:
  email: false
